[package]
name = "file-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.28.1"
rustix = "0.38.36"
sysinfo = "0.31.4"
users = "0.11.0"
uuid = { version = "1.10.0", features = ["v4"]}
